// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
